### ISSUE TITLE
Issues with Enum types

### ISSUE THREAD

**Issue by apalala** [tamuhey/dataclass_utils#2]
I have this definition:

```python
@dataclass
class Detail
    class DetailType(Enum):
        MOVIE = 'movie'
        MOVIE_BUNDLE = 'movie_bundle'
        TV_SHOW = 'tv_show'
        TV_SEASON = 'tv_season'
```
and then:

```python
    detail_type: DetailType = ''
```
the above fails because the library doesn't know `DetailType`

This removes the previous error, but a value of type `str` is allowed:

```python
    detail_type: DetailItem.DetailType = ''
```

**Comment by tamuhey** [comment]
Thanks for reporting issue.

The code below is not valid, so Pyright and Mypy reports "value not defined":

```python
    detail_type: DetailType = ''"
```

but the code below is valid, so Pyright and Mypy reports "type issue":

```python
a: Detail.DetailType = ""
```

I'll try to add feature for enum.

**Comment by tamuhey** [comment]
I've added test code for enum and confirmed this library properly works for enum:

https://github.com/tamuhey/dataclass_utils/commit/f98d7db8d061a85e1def29c8d20399c5ca2e630f#diff-959a1effd1cb0e25016584deef9be1994af65814f318346bf3a63801b5db1636R200
