### ISSUE TITLE
Projects that want typing-extensions >= 4.0 cannot use this library

### ISSUE THREAD

**Issue by klbostee** [tamuhey/dataclass_utils#5]
Since poetry automatically puts an upper bound on dependency versions, `typing-extensions` is limited to `<4.0` as well as `>=3.10`. This means that one cannot use a recent `typing-extensions` when using `dataclass-utils`, while `typing-extensions` 4.2 still supports python 3.7 which is already the minimum python version for `dataclass-utils` anyway.

**Comment by tamuhey** [comment]
Thanks for reporting the issue! Could you please create a Pull Request? @klbostee

**Comment by klbostee** [comment]
Just created a PR. You'll still have to do a release to actually fix the problem though.

**Comment by tamuhey** [comment]
@klbostee Thank you for your help! I've just published the new version [0.7.20](https://pypi.org/project/dataclass-utils/).
