### ISSUE TITLE
Support for variable length tuples

### ISSUE THREAD

**Issue by llucid-97** [tamuhey/dataclass_utils#7]
Hi, I've been using your library, loving it so far, but I've run into an issue:

I have a dataclass which has a tuple of integers.
I don't know how long the tuple will be at run time.

```python
from dataclasses import dataclass
from dataclass_utils import check_type
from typing import Tuple

@dataclass
class Foo:
    bar: Tuple[int,...] = (1,2,3)

check_type(Foo())
```
According to [python's typing rules](https://docs.python.org/3/library/typing.html#typing.Tuple), this should pass, but it doesn't:

> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "D:/projects/fastpbrl-main/scripts/scratchpads/check_types.py", line 8, in <module>
>     check_type(Foo())
>   File "D:\Users\agimg\Miniconda3\envs\clockwork_mind\lib\site-packages\dataclass_utils\type_checker.py", line 181, in check_root
>     raise err
> dataclass_utils.error.Error0: Error in field 'bar'. Expected type typing.Tuple[int, ...], got <class 'tuple'> (value: (1, 2, 3))
> python-BaseException

**Comment by tamuhey** [comment]
@llucid-97 Thanks for reporting a bug. I'll try to fix that.
